name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
    - name: Construir a imagem do containet docker
      run: echo "Executar o docker buld"
    - name: Efetuar login no docker hub
      run: echo "Executar o docker hub"
    - name: Enviar docker para o registry
      run: echo "Executar o docker push"  
    
