name: CI-CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Efetuar login no docker hub
      run: echo "executar o docker login"
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}  
    - name: Construir a imagem do container docker
      run: "executar o docker build"
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: | 
          douginfodev/kube-news:${{ github.run_number}}
          douginfodev/kube-news:latest
          
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
    - name: Autenticar na aws
      run: "Fazer o login no aws"
    - name: Configurar o Kubeconfig
      run: echo "Configurar o Kubeconfig"
    - name: Aplicar o Deploy
      run: echo "Executar o kubectl apply"
